# Import packages

In [3]:
from sklearn.linear_model import LogisticRegression as LR
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
import pandas as pd
import numpy as np

# Step 1: Load data

In [4]:
data = pd.read_csv('Social_Network_Ads.csv')

# Step 2: Preprocessing

In [5]:
# use 300 people's age, estimated ,and gender salary to train data
label_encoder = preprocessing.LabelEncoder()
encoded_Gender = label_encoder.fit_transform(data["Gender"])
data["Gender"] = encoded_Gender

X = data[['Gender', 'Age', 'EstimatedSalary']].values
Y = data[['Purchased']].values

print("X={}, Shape={}".format(X, np.shape(X)))
print("Y={}, Shape={}".format(Y, np.shape(Y)))

X=[[1.0e+00 1.9e+01 1.9e+04]
 [1.0e+00 3.5e+01 2.0e+04]
 [0.0e+00 2.6e+01 4.3e+04]
 ...
 [0.0e+00 5.0e+01 2.0e+04]
 [1.0e+00 3.6e+01 3.3e+04]
 [0.0e+00 4.9e+01 3.6e+04]], Shape=(400, 3)
Y=[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [

# Step 3: Train model(LogisticRegression, SVM)

In [13]:
Train_X, Test_X, Train_Y, Test_Y = train_test_split(X,Y,test_size=0.25, random_state=0)

# Ref from https://tinyurl.com/y4pr2f4r
sc = preprocessing.StandardScaler()
Train_X = sc.fit_transform(Train_X)
Test_X = sc.transform(Test_X)

model = LR()
svm_model = SVC(kernel='linear', probability=True)

predY = model.fit(Train_X, Train_Y).predict(Test_X)
predY_WITH_SVM = svm_model.fit(Train_X, Train_Y).predict(Test_X)

//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
//anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
//anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Step 4 : Get Accuracy

In [15]:
print("Prediction accuracy is {}".format(accuracy_score(predY, Test_Y)))
print("Prediction probability is {}".format(model.predict_proba(Test_X)))
print("#####################################")
print("Prediction accuracy by using SVM is {}".format(accuracy_score(predY_WITH_SVM, Test_Y)))
print("Prediction probability by using SVM is {}".format(svm_model.predict_proba(Test_X)))

Prediction accuracy is 0.91
Prediction probability is [[0.87565486 0.12434514]
 [0.84279008 0.15720992]
 [0.78723936 0.21276064]
 [0.91631266 0.08368734]
 [0.90863568 0.09136432]
 [0.99122582 0.00877418]
 [0.98590801 0.01409199]
 [0.24614471 0.75385529]
 [0.9946178  0.0053822 ]
 [0.46677072 0.53322928]
 [0.95989929 0.04010071]
 [0.97282721 0.02717279]
 [0.82351637 0.17648363]
 [0.60349062 0.39650938]
 [0.9827739  0.0172261 ]
 [0.68087104 0.31912896]
 [0.69677759 0.30322241]
 [0.98637507 0.01362493]
 [0.01214716 0.98785284]
 [0.95324085 0.04675915]
 [0.91634435 0.08365565]
 [0.03911553 0.96088447]
 [0.73671899 0.26328101]
 [0.10627308 0.89372692]
 [0.99583663 0.00416337]
 [0.02884052 0.97115948]
 [0.92741581 0.07258419]
 [0.9155435  0.0844565 ]
 [0.81738715 0.18261285]
 [0.85269732 0.14730268]
 [0.97754592 0.02245408]
 [0.6830023  0.3169977 ]
 [0.06063547 0.93936453]
 [0.8326814  0.1673186 ]
 [0.98403966 0.01596034]
 [0.99613012 0.00386988]
 [0.97796786 0.02203214]
 [0.93868524 0.061314